server {
	listen 2500;
    host 127.0.0.1;
    server_name localhost;
    client_max_body_size 1000000;

    location / {
        root ./www;
        index index.html;
        upload_store /uploads;
        allow_methods GET POST;
    }
}
