server {
	listen 2500;
    host 127.0.0.1;
    server_name localhost;
    client_max_body_size 1000000;

    location / {
        root ./www/htmlup;
        index index.html;
        allow_methods GET;
    }
}

server {
    listen 3000;
    server_name localhost;
    host 127.0.0.1;


    location /cgi-bin {
        root ./www;
        allow_methods GET;
        cgi_pass .py /usr/bin/python3;
        cgi_pass .php /usr/bin/php-cgi;
    }
}